project:
  type: website
  site-dir: _site
website:
  title: "Nerd-or-Geek Portfolio"
  favicon: NOG.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: "#projects"
    right:
      - text: "GitHub"
        href: https://github.com/Nerd-or-Geek
  search: true
  sidebar:
    style: "docked"
    contents:
      - section: Projects
        contents:
          - pinecraft-raspberry-pi/pinecraft-raspberry-pi.qmd
  page-footer:
    left: |
      &copy; 2026 [Nerd-or-Geek](https://github.com/Nerd-or-Geek) &mdash; [Repository](https://github.com/Nerd-or-Geek/Nerd-or-Geek.github.io)
    right: |
      [Contact](mailto:contact@example.com) | [YouTube](https://youtube.com/@Nerd-or-Geek) | [Twitter](https://twitter.com/NerdorGeek)
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
