project:
  type: website
site:
  title: "Nerd-or-Geek Documentation Hub"
website:
  favicon: NOG.png
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Projects
        menu:
          - text: Pinecraft on Raspberry Pi
            file: pinecraft-raspberry-pi/pinecraft-raspberry-pi.qmd
    right:
      - icon: github
        href: https://github.com/Nerd-or-Geek
  search: true
  sidebar:
    style: "docked"
    contents:
      - section: Projects
        contents:
          - pinecraft-raspberry-pi/pinecraft-raspberry-pi.qmd
  page-footer:
    left: |
      &copy; 2026 [Nerd-or-Geek](https://github.com/Nerd-or-Geek) &mdash; [Repository](https://github.com/Nerd-or-Geek/Nerd-or-Geek.github.io)
    right: |
      [Contact](mailto:contact@example.com) | [YouTube](https://youtube.com/@Nerd-or-Geek) | [Twitter](https://twitter.com/NerdorGeek)
format:
  html:
    theme: default
    css: styles.css
    toc: true
